export const buttonTheme = {
  base: "flex items-center justify-center gap-2 px-4 py-2 font-medium transition-all duration-300 cursor-pointer w-10 h-10",
  rounded: {
    none: "rounded-none",
    sm: "rounded-sm",
    md: "rounded-md",
    full: "rounded-full",
  },
  variant: {
    contained: {
      primary: "bg-[var(--primary)] text-foreground hover:bg-[var(--primary-hover)]",
      secondary: "bg-[var(--secondary)] text-[var(--foreground)] hover:bg-[var(--secondary-hover)]",
      success: "bg-[var(--success)] text-white hover:bg-[var(--success-hover)]",
      danger: "bg-[var(--danger)] text-white hover:bg-[var(--danger-hover)]",
      warning: "bg-[var(--warning)] text-white hover:bg-[var(--warning-hover)]",
      info: "bg-[var(--info)] text-white hover:bg-[var(--info-hover)]",
      muted: "bg-[var(--muted)] text-white hover:bg-[var(--muted-hover)]",
      selected: "bg-[var(--foreground)] text-[var(--primary)] hover:bg-[var(--primary-hover)] hover:text-[var(--main-hover)]",
    },
    outlined: {
      primary: "border-2 border-[var(--primary)] text-[var(--primary)] hover:bg-[var(--primary-hover)] hover:bg-opacity-10",
      secondary: "border border-[var(--secondary)] text-[var(--secondary)] hover:bg-[var(--secondary-hover)] hover:bg-opacity-10",
      success: "border border-[var(--success)] text-[var(--success)] hover:bg-[var(--success-hover)] hover:bg-opacity-10",
      danger: "border border-[var(--danger)] text-[var(--danger)] hover:bg-[var(--danger-hover)] hover:bg-opacity-10",
      warning: "border border-[var(--warning)] text-[var(--warning)] hover:bg-[var(--warning-hover)] hover:bg-opacity-10",
      info: "border-2 border-[var(--info)] text-[var(--info)] hover:border-[var(--info-hover)] hover:text-[var(--info-hover)] hover:bg-[var(--info-hover)]/10",
      muted: "border border-[var(--muted)] text-[var(--muted)] hover:bg-[var(--muted-hover)] hover:bg-opacity-10",
      selected: "border border-[var(--foreground)] text-[var(--primary)] hover:bg-gray-200 hover:bg-opacity-10",
    },
    plain: {
      primary: "text-[var(--primary)] hover:bg-[var(--primary-hover)] hover:bg-opacity-10",
      secondary: "text-[var(--secondary)] hover:bg-[var(--secondary-hover)] hover:bg-opacity-10",
      success: "text-[var(--success)] hover:bg-[var(--success-hover)] hover:bg-opacity-10",
      danger: "text-[var(--danger)] hover:bg-[var(--danger-hover)] hover:bg-opacity-10",
      warning: "text-[var(--warning)] hover:bg-[var(--warning-hover)] hover:bg-opacity-10",
      info: "text-[var(--info)] hover:bg-[var(--info-hover)]/10",
      muted: "text-[var(--muted)] hover:bg-[var(--muted-hover)] hover:bg-opacity-10",
      selected: "text-[var(--primary)] hover:bg-gray-200 hover:bg-opacity-10",
    },
    ghost: {
      primary: "text-[var(--primary)] hover:bg-[var(--primary-hover)] hover:bg-opacity-20 dark:hover:bg-opacity-30",
      secondary: "text-[var(--secondary)] hover:bg-[var(--secondary-hover)] hover:bg-opacity-20 dark:hover:bg-opacity-30",
      success: "text-[var(--success)] hover:bg-[var(--success-hover)] hover:bg-opacity-20 dark:hover:bg-opacity-30",
      danger: "text-[var(--danger)] hover:bg-[var(--danger-hover)] hover:bg-opacity-20 dark:hover:bg-opacity-30",
      warning: "text-[var(--warning)] hover:bg-[var(--warning-hover)] hover:bg-opacity-20 dark:hover:bg-opacity-30",
      info: "text-[var(--info)] hover:bg-[var(--info-hover)] hover:bg-opacity-20 dark:hover:bg-opacity-30",
      muted: "text-[var(--muted)] hover:bg-[var(--muted-hover)] hover:bg-opacity-20 dark:hover:bg-opacity-30",
      selected: "text-[var(--primary)] hover:bg-gray-200 hover:bg-opacity-20 dark:hover:bg-opacity-30",
    },
    soft: {
      primary: "bg-[var(--primary)] bg-opacity-10 text-[var(--primary)] hover:bg-[var(--primary-hover)] hover:bg-opacity-20",
      secondary: "bg-[var(--secondary)] bg-opacity-10 text-[var(--secondary)] hover:bg-[var(--secondary-hover)] hover:bg-opacity-20",
      success: "bg-[var(--success)] bg-opacity-10 text-[var(--success)] hover:bg-[var(--success-hover)] hover:bg-opacity-20",
      danger: "bg-[var(--danger)] bg-opacity-10 text-[var(--danger)] hover:bg-[var(--danger-hover)] hover:bg-opacity-20",
      warning: "bg-[var(--warning)] bg-opacity-10 text-[var(--warning)] hover:bg-[var(--warning-hover)] hover:bg-opacity-20",
      info: "bg-[var(--info)] bg-opacity-10 text-[var(--info)] hover:bg-[var(--info-hover)] hover:bg-opacity-20",
      muted: "bg-[var(--muted)] bg-opacity-10 text-[var(--muted)] hover:bg-[var(--muted-hover)] hover:bg-opacity-20",
      selected: "bg-[var(--foreground)] bg-opacity-10 text-[var(--primary)] hover:bg-gray-200 hover:bg-opacity-20",
    },
    link: {
      primary: "text-[var(--primary)] underline hover:text-[var(--primary-hover)]",
      secondary: "text-[var(--secondary)] underline hover:text-[var(--secondary-hover)]",
      success: "text-[var(--success)] underline hover:text-[var(--success-hover)]",
      danger: "text-[var(--danger)] underline hover:text-[var(--danger-hover)]",
      warning: "text-[var(--warning)] underline hover:text-[var(--warning-hover)]",
      info: "text-[var(--info)] underline hover:text-[var(--info-hover)]",
      muted: "text-[var(--muted)] underline hover:text-[var(--muted-hover)]",
      selected: "text-[var(--primary)] underline hover:text-gray-200",
    },
  },
};